### ISSUE TITLE
export kml functionality

### ISSUE THREAD

**Issue by haze1986** [NOAA-PMEL/las9#44]
Hi I was exploring LAS9 further and it seems that the export kml functionality is no longer in LAS9. Would this be easy to implement back? This is to allow users to download the kml and overlay it on google earth

**Comment by noaaroland** [comment]
In my opinion there are other tools which do this job better. Either https://github.com/Reading-eScience-Centre/ncwms or it's manifestation in THREDDS can provide map images which can be overlaid in Google Earth. Given those options I'm not inclined to bring back our implementation which was complicated and less functional.
