### ISSUE TITLE
Issues migrating to 9.8.1

### ISSUE THREAD

**Issue by haze1986** [NOAA-PMEL/las9#54]
Hi Roland,

I was having issues updating to the later LAS version, noting that I have to upgrade to new thredds, and also upgrading to Java 11 and tomcat 9. I was trying to revamp the server with the recommended new versions based on the official guide. I am having issues at the step where likely Java is causing issues with dozens of erros shown as below

`processURLs Failed to scan [file:/usr/local/apache-tomcat-9.0.73/webapps/las%23thredds/WEB-INF/`

That seems like the only thing that I did different from the guide as I cant download from sdkman. I was using the same version of Java downloaded from adoptium, would this be an issue?

`
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Temurin-11.0.12+7 (build 11.0.12+7, mixed mode)
`

Update with log:
[LASlog.txt](https://github.com/NOAA-PMEL/las9/files/11026205/LASlog.txt)

**Comment by haze1986** [comment]
Ok, to clarify I could access apache tomcat when the server loads. But the page /las was not found. The full log did not show a specific error loading las.war.
Can you share the Java tar gz link you've used? Trying to eliminate Java as the issue.

**Comment by noaaroland** [comment]
Do you see an messages after the LAS start up? Like:

14:43:50.015 [main] INFO  pmel.sdig.las.InitializationService - This is las verison 9.8.1

I don't know how to reference the Java I used except by the name for the target in sdkman.

**Comment by haze1986** [comment]
2023-03-21 11:16:59,452 main ERROR FileManager (../content/ftds/logs/serverStartup.log) java.io.IOException: Could not create directory /usr/local/content/ftds/logs java.io.IOException: Could not create directory /usr/local/content/ftds/logs

ok could be here, i think it try to create directory in /usr/local and not the specified directory with write access. Did I do something wrong here?

**Comment by noaaroland** [comment]
Try it will all of the directories in $TOMCAT_HOME/content.
$TOMCAT_HOME/content/las
$TOMCAT_HOME/content/ftds
$TOMCAT_HOME/content/thredds if you have your own TDS running.
and be sure to set -Dftds.content.dir and -Dtds.content.root.path (first one is [ful_path]/content/ftds and the second is [full_path]/content

**Comment by haze1986** [comment]
Thanks Roland.

Following and making sure all directories are created, it works now.
