### ISSUE TITLE
Global map not being displayed on Axes Selection

### ISSUE THREAD

**Issue by jessicaborgesp** [NOAA-PMEL/las9#56]
Hello! I noticed that with the current version I am not being able to see the global map on axes selection, I just see a pink background. I thought it might be only with my server but I also opened https://data.pmel.noaa.gov/aclim/las and I saw the same issue there. This is what I see:

![image](https://github.com/NOAA-PMEL/las9/assets/50730584/3a3ecadf-d979-4102-b7d4-53e6abb258f2)

This is the error when I use inspect:

```
UI.html#%7B%22id%22:…:%221%22%7D%5D%7D:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

DevTools failed to load source map: Could not load content for https://data.pmel.noaa.gov/aclim/las/interact.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

It looks like the map is not loading, is the image missing?
Thank you!

**Comment by noaaroland** [comment]
We do not have our own tile server to provide the map tiles for the mini map. We depend on other sites which generously make compatible map tiles available for free. Sometimes those sites stop serving tiles temporarily or sometimes permanently.

The information for how to configure LAS to use a variety of different map tile servers is available at the top of the the UI.html, UI.vm and getUI.do files which are distributed with LAS.

I just switched the ACLIM server to use:

    <meta content="http://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv" name="WMS-SERVER" id="wms-server" />
    <meta content="GEBCO_LATEST" name="WMS-LAYER" id="wms-layer" />

You can do the same with your server, but in truth the osgeo server has been the most reliable over the decades and it's likely that the unavailability of tiles from that source is only temporary.

![image](https://github.com/NOAA-PMEL/las9/assets/16550018/f023d82f-4f54-4483-85ff-c2edd0108447)
