### ISSUE TITLE
problem with java, tried different versions

### ISSUE THREAD

**Issue by haze1986** [NOAA-PMEL/las9#84]
/usr/local/las.v8.6.13/JavaSource/gov/noaa/pmel/tmap/las/jdom/LASBackendResponse.java:41: error: package com.sun.rowset is not visible
    [javac] import com.sun.rowset.WebRowSetImpl;
    [javac]

**Comment by noaaroland** [comment]
Specifically which versions of Java did you try? The webrow set is a depreciated API, but it is still available in the OpenJDK 1.8 which is our current recommendation for Java a version of which you can get nicely packaged here:

https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot

OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
javac 1.8.0_275
